"c:\Program Files\Inkscape\inkscape.com" 2-chairs.svg                                  -y 1.0 -z -b "#ffffff" -D -e 2-chairs.png
"c:\Program Files\Inkscape\inkscape.com" A-ZOR-B-examples.svg                          -y 1.0 -z -b "#ffffff" -D -e A-ZOR-B-examples.png
"c:\Program Files\Inkscape\inkscape.com" and-or-graph.svg                              -y 1.0 -z -b "#ffffff" -D -e and-or-graph.png
"c:\Program Files\Inkscape\inkscape.com" Atomspace-based-architecture.svg              -y 1.0 -z -b "#ffffff" -D -e Atomspace-based-architecture.png
"c:\Program Files\Inkscape\inkscape.com" B-Z-conditional.svg                           -y 1.0 -z -b "#ffffff" -D -e B-Z-conditional.png
"c:\Program Files\Inkscape\inkscape.com" BayesNet-alarm-John.svg                       -y 1.0 -z -b "#ffffff" -D -e BayesNet-alarm-John.png
"c:\Program Files\Inkscape\inkscape.com" BayesNet-successful-business.svg              -y 1.0 -z -b "#ffffff" -D -e BayesNet-successful-business.png
"c:\Program Files\Inkscape\inkscape.com" BDI-architecture.svg                          -y 1.0 -z -b "#ffffff" -D -e BDI-architecture.png
"c:\Program Files\Inkscape\inkscape.com" Ben-see-Josh.svg                              -y 1.0 -z -b "#ffffff" -D -e Ben-see-Josh.png
"c:\Program Files\Inkscape\inkscape.com" Beta-distro-watershed.svg                     -y 1.0 -z -b "#ffffff" -D -e Beta-distro-watershed.png
"c:\Program Files\Inkscape\inkscape.com" Beta-distro-watershed1.svg                    -y 1.0 -z -b "#ffffff" -D -e Beta-distro-watershed1.png
"c:\Program Files\Inkscape\inkscape.com" binary-and-fuzzy-character.svg                -y 1.0 -z -b "#ffffff" -D -e binary-and-fuzzy-character.png
"c:\Program Files\Inkscape\inkscape.com" binary-fuzzy-unary-characters.svg             -y 1.0 -z -b "#ffffff" -D -e binary-fuzzy-unary-characters.png
"c:\Program Files\Inkscape\inkscape.com" business-model.svg                            -y 1.0 -z -b "#ffffff" -D -e business-model.png
"c:\Program Files\Inkscape\inkscape.com" chicken-and-egg1.svg                          -y 1.0 -z -b "#ffffff" -D -e chicken-and-egg1.png
"c:\Program Files\Inkscape\inkscape.com" combined-architecture.svg                     -y 1.0 -z -b "#ffffff" -D -e combined-architecture.png
"c:\Program Files\Inkscape\inkscape.com" Common Logic API.svg                          -y 1.0 -z -b "#ffffff" -D -e Common Logic API.png
"c:\Program Files\Inkscape\inkscape.com" complete-architecture.svg                     -y 1.0 -z -b "#ffffff" -D -e complete-architecture.png
"c:\Program Files\Inkscape\inkscape.com" fuzzy-modifiers-triangular.svg                -y 1.0 -z -b "#ffffff" -D -e fuzzy-modifiers-triangular.png
"c:\Program Files\Inkscape\inkscape.com" Gamma-for-lukewarm.svg                        -y 1.0 -z -b "#ffffff" -D -e Gamma-for-lukewarm.png
"c:\Program Files\Inkscape\inkscape.com" Gaussian-fuzzy-modifier-regression-result.svg -y 1.0 -z -b "#ffffff" -D -e Gaussian-fuzzy-modifier-regression-result.png
"c:\Program Files\Inkscape\inkscape.com" Geniferology-title.svg                        -y 1.0 -z -b "#ffffff" -D -e Geniferology-title.png
"c:\Program Files\Inkscape\inkscape.com" Java-girl.svg                                 -y 1.0 -z -b "#ffffff" -D -e Java-girl.png
"c:\Program Files\Inkscape\inkscape.com" KBMC-illustrated.svg                          -y 1.0 -z -b "#ffffff" -D -e KBMC-illustrated.png
"c:\Program Files\Inkscape\inkscape.com" minimal-arch.svg                              -y 1.0 -z -b "#ffffff" -D -e minimal-arch.png
"c:\Program Files\Inkscape\inkscape.com" neutral-point.svg                             -y 1.0 -z -b "#ffffff" -D -e neutral-point.png
"c:\Program Files\Inkscape\inkscape.com" new-architecture-1.svg                        -y 1.0 -z -b "#ffffff" -D -e new-architecture-1.png
"c:\Program Files\Inkscape\inkscape.com" new-architecture-2.svg                        -y 1.0 -z -b "#ffffff" -D -e new-architecture-2.png
"c:\Program Files\Inkscape\inkscape.com" new-architecture-3.svg                        -y 1.0 -z -b "#ffffff" -D -e new-architecture-3.png
"c:\Program Files\Inkscape\inkscape.com" Ouroboros-simple.svg                          -y 1.0 -z -b "#ffffff" -D -e Ouroboros-simple.png
"c:\Program Files\Inkscape\inkscape.com" Ouroboros.svg                                 -y 1.0 -z -b "#ffffff" -D -e Ouroboros.png
"c:\Program Files\Inkscape\inkscape.com" P(Z) commutative diagram.svg                  -y 1.0 -z -b "#ffffff" -D -e P(Z) commutative diagram.png
"c:\Program Files\Inkscape\inkscape.com" prelogic.svg                                  -y 1.0 -z -b "#ffffff" -D -e prelogic.png
"c:\Program Files\Inkscape\inkscape.com" Procedural-subsumes-Declarative-system.svg    -y 1.0 -z -b "#ffffff" -D -e Procedural-subsumes-Declarative-system.png
"c:\Program Files\Inkscape\inkscape.com" rich-vs-powerful.svg                          -y 1.0 -z -b "#ffffff" -D -e rich-vs-powerful.png
"c:\Program Files\Inkscape\inkscape.com" roadmap1.svg                                  -y 1.0 -z -b "#ffffff" -D -e roadmap1.png
"c:\Program Files\Inkscape\inkscape.com" self-programming-architecture.svg             -y 1.0 -z -b "#ffffff" -D -e self-programming-architecture.png
"c:\Program Files\Inkscape\inkscape.com" spatial-inference.svg                         -y 1.0 -z -b "#ffffff" -D -e spatial-inference.png
"c:\Program Files\Inkscape\inkscape.com" spatial-vs-logical.svg                        -y 1.0 -z -b "#ffffff" -D -e spatial-vs-logical.png
"c:\Program Files\Inkscape\inkscape.com" substitution-management.svg                   -y 1.0 -z -b "#ffffff" -D -e substitution-management.png
"c:\Program Files\Inkscape\inkscape.com" Thinker-Actor.svg                             -y 1.0 -z -b "#ffffff" -D -e Thinker-Actor.png
"c:\Program Files\Inkscape\inkscape.com" Wang-vs-YKY-confidence-squashing-fn.svg       -y 1.0 -z -b "#ffffff" -D -e Wang-vs-YKY-confidence-squashing-fn.png
"c:\Program Files\Inkscape\inkscape.com" Z-modifiers.svg                               -y 1.0 -z -b "#ffffff" -D -e Z-modifiers.png
"c:\Program Files\Inkscape\inkscape.com" Z1-Gaussian-transform-to-Z0-ugly.svg          -y 1.0 -z -b "#ffffff" -D -e Z1-Gaussian-transform-to-Z0-ugly.png
"c:\Program Files\Inkscape\inkscape.com" z1-OR-z2-10-cases.svg                         -y 1.0 -z -b "#ffffff" -D -e z1-OR-z2-10-cases.png
"c:\Program Files\Inkscape\inkscape.com" z1-OR-z2-M-and-V-plots.svg                    -y 1.0 -z -b "#ffffff" -D -e z1-OR-z2-M-and-V-plots.png
"c:\Program Files\Inkscape\inkscape.com" Zhineng-logo.svg                              -y 1.0 -z -b "#ffffff" -D -e Zhineng-logo.png
